"""Sync DB with current models

Revision ID: 12fa21c32649
Revises: 4ee96d480799
Create Date: 2025-05-26 18:10:05.058278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fa21c32649'
down_revision: Union[str, None] = '4ee96d480799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'builds', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'builds', type_='foreignkey')
    op.drop_column('builds', 'created_at')
    # ### end Alembic commands ###
